FROM python:3.9

COPY .stocks_products/requirements.txt /stocks_products/requirements.txt
RUN pip3 install --no-cache-dir --upgrade -r /stocks_products/requirements.txt
COPY .stocks_products /stocks_products
EXPOSE 6060
ENV SECRET_KEY django-insecure-nw^y+m^wmxza1asgk+)!ua2qx9)g+#v=6%76-9i8i(6eqiw94j
ENV DEBUG 1
WORKDIR stocks_products

CMD ["python","manage.py","runserver", "0.0.0.0:6060"]
